export const MOVE_PLAYER = 'MOVE_PLAYER'
export const MOVE_BACKGROUND = 'MOVE_BACKGROUND'
export const ADD_OBSTACLES = 'ADD_OBSTACLES'
export const REMOVE_OBSTACLES = 'REMOVE_OBSTACLES'
export const LOSE_GAME = 'LOSE_GAME'
export const RESET_GAME_PLAYER = 'RESET_GAME_PLAYER'
export const RESET_GAME_BACKGROUND = 'RESET_GAME_BACKGROUND'
export const RESET_GAME = 'RESET_GAME'
export const RESET_GAME_OBSTACLES = 'RESET_GAME_OBSTACLES'


