export const MOVE_PLAYER = 'MOVE_PLAYER'
export const MOVE_BACKGROUND = 'MOVE_BACKGROUND'
export const STOP_BACKGROUND = 'STOP_BACKGROUND'
export const ADD_OBSTACLES = 'ADD_OBSTACLES'
export const MOVE_OBSTACLES = 'MOVE_OBSTACLES'
export const REMOVE_OBSTACLES = 'REMOVE_OBSTACLES'



